POST 127.0.0.1:8080/record/
content-type: application/json
Authorization: Bearer

{
  "filename":"SignInWithPasswordResponse.kt",
  "tag": "",
  "major_drive": "ahxodzzqq2",
  "minor_drive": "D",
  "path": "/healox/SignInWithPasswordResponse.kt"
}